					.basictab ul {
					margin: 4px;
					padding: 3px 0;
					margin-left: 0;
					font: bold 10px Verdana;
					width:99%;
					border-bottom: 1px solid gray;
					list-style-type: none;
					text-align: left; /*set to left, center, or right to align the menu as desired*/
					margin-bottom:0px;
					}
					.basictab li{
					display: inline;
					margin: 0;
					}
					.basictab li a{
					text-decoration: none;
					padding: 3px 7px;
					margin-right: 3px;
					border: 1px solid grey;
					border-bottom: none;
					background-color: #ffffff;
					color: #2d2b2b;
					}
					.basictab li a:visited{
					color: #2d2b2b;
					}
					.basictab li a:hover {
					color: black;
					}
					.basictab li a.current{
					background-color: #E7DBA8;
					color: black;
					}
					.basictab li a:active{
					color: black;
					}
					#tabcontentcontainer{
					width:98%; /*width of 2nd level content*/
					height:220px; /*height of 2nd level content. Set to largests content height to avoid jittering.*/
					border-bottom: 1px solid grey;
					border-right: 1px solid grey;
					border-left: 1px solid grey;
					padding-left:5px;
					padding-top:5px;
					margin-top:0px;
					}
					.tabcontent{
					display:none;
					padding-left:1px;
					padding-bottom:10px;
					min-height:165px;
					}
					TABLE#langTable {
					margin-top: 10px;
					}
					TABLE#langTable TR TD {
					padding-left : 2px;
					padding-right : 2px;
					white-space: nowrap;
					}
					TD.c-blocked { background-color: red; }
					TD.c-ok { background-color: #669966; }
					TD.c-fallback {  }
					TD.c-leftLine {border-left: 2px solid black; }
					.bgColor5 { font-weight: bold; }
					DIV.warning { border: 1px solid grey; padding:5px; color:red; }
					DIV.green { border: 1px solid grey; padding:5px; color:green; }
					.green { color:green; }
					.message { color:#000000; text-align:left }
					DIV.report { border: 1px solid grey; padding:5px; }
					DIV.right { text-align:center; }
					TD.printOpts { vertical-align:top; }
					TD.error { color:red; vertical-align:top; text-align:left; }
